using SafeTestsets

const GROUPS = isempty(ARGS) ?
               (Sys.isapple() && Sys.ARCH === :aarch64 ? ["core", "slow", "metal"] :
                ["core", "slow"]) : ARGS

if "core" in GROUPS
    @safetestset "Exports                      " include("integration/exports.jl")
    @safetestset "Public surface               " include("integration/public_surface.jl")
    @safetestset "Aqua: piracy and compat      " include("quality/aqua.jl")
    @safetestset "JET                          " include("quality/jet.jl")
    @safetestset "ExplicitImports              " include("quality/explicit_imports.jl")
    @safetestset "Own-vs-own ambiguities       " include("ambiguities.jl")
    @safetestset "Container/section copies     " include("optimizers/container_section_copy.jl")
    @safetestset "Stiefel Manifold             " include("manifolds/stiefel_manifold.jl")
    @safetestset "Grassmann Manifold           " include("manifolds/grassmann_manifold.jl")
    @safetestset "Manifold Broadcast           " include("manifolds/broadcast.jl")
    @safetestset "Symplectic Stiefel Manifold  " include("manifolds/symplectic_stiefel_manifold.jl")
    @safetestset "Symplectic on a backend      " include("manifolds/symplectic_backend.jl")
    @safetestset "Symplectic SR Decomposition  " include("decompositions/symplectic_sr.jl")
    @safetestset "Backend default eltype       " include("integration/default_eltype.jl")
    @safetestset "Backend eltype check         " include("integration/backend_eltype_check.jl")
    @safetestset "Stiefel Projection           " include("special_matrices/stiefel_projetion.jl")
    @safetestset "Skew-Symmetric Matrix        " include("special_matrices/skew_symmetric.jl")
    @safetestset "Symmetric Matrix             " include("special_matrices/symmetric_matrix.jl")
    @safetestset "ProjectTo natural cotangent  " include("special_matrices/project_to.jl")
    @safetestset "Triangular Matrices          " include("special_matrices/triangular.jl")
    @safetestset "Mutating Return Values       " include("special_matrices/scalar_mul_return_value.jl")
    @safetestset "Optimizer Primitives         " include("special_matrices/optimizer_primitives.jl")
    @safetestset "Elementwise primitives       " include("optimizers/named_tuple_wrapper.jl")
    @safetestset "Error-only methods           " include("integration/error_only_methods.jl")
    @safetestset "Grassmann Lie Alg Hor        " include("lie_algebras/grassmann_lie_algebra_horizontal.jl")
    @safetestset "Stiefel Lie Alg Hor          " include("lie_algebras/stiefel_lie_algebra_horizontal.jl")
    @safetestset "Retractions                  " include("retractions/retractions.jl")
    @safetestset "Exponential Accuracy         " include("retractions/exponential_accuracy.jl")
    @safetestset "In-place 𝔄                   " include("retractions/modified_exponential.jl")
    @safetestset "Retraction workspace         " include("retractions/retraction_workspace.jl")
    @safetestset "Ω functions                  " include("global_sections/omega_functions.jl")
    @safetestset "Global global_sections       " include("global_sections/global_sections.jl")
    @safetestset "Optimizer Convergence        " include("verification/svd_optim.jl")
    @safetestset "Optimizers                   " include("integration/optimizer_tests.jl")
    @safetestset "Optimizer phase observer     " include("integration/optimizer_observer.jl")
    @safetestset "Optimizer Problems           " include("optimizers/optimizer_problems.jl")
    @safetestset "Optimizer Status             " include("optimizers/optimizer_status_tests.jl")
    @safetestset "Descent Direction            " include("optimizers/descent_direction_tests.jl")
    @safetestset "Quasi-Newton Secant Pair     " include("optimizers/quasi_newton_secant_tests.jl")
    @safetestset "Manifold Line Search         " include("integration/manifold_linesearch_tests.jl")
    @safetestset "Trial slope in a workspace   " include("optimizers/linesearch_problem.jl")
    @safetestset "BFGS state update            " include("optimizers/iterative_hessians/bfgs/bfgs_state.jl")
    @safetestset "Manifold Optimizers          " include("integration/manifold_optimizers_with_new_interface.jl")
    @safetestset "Grassmann Optimizers         " include("integration/grassmann_optimizer_tests.jl")
    @safetestset "Optimizer State Init         " include("manifold_optimizers/optimizer_state_initialization.jl")
    @safetestset "Optimizer State Accessors    " include("integration/optimizer_state_accessors.jl")
    @safetestset "Optimizer State Semantics    " include("integration/optimizer_state_semantics.jl")
    @safetestset "Optimizer Step Formulas      " include("manifold_optimizers/optimizer_step_formulas.jl")
    @safetestset "Adam + Euclidean decay       " include("manifold_optimizers/adam_with_euclidean_decay_optimizer.jl")
    @safetestset "Adam + decaying step         " include("optimizers/decaying_static.jl")
    @safetestset "Scalar-moment Adam           " include("manifold_optimizers/scalar_moment_adam_optimizer.jl")
    @safetestset "Training step                " include("integration/training_optimizer.jl")
    @safetestset "Flat Parameters              " include("integration/flat_parameters.jl")
    @safetestset "NeuralNetworkParameters      " include("integration/neural_network_parameters_protocol.jl")
    @safetestset "Container Parameters         " include("integration/network_parameters_optimizer.jl")
    @safetestset "Flat Buffer Allocations      " include("integration/flat_buffer_allocations.jl")
    @safetestset "changebackend                " include("integration/changebackend.jl")
    @safetestset "similar keeps the backend    " include("integration/similar_backend.jl")
    @safetestset "rgrad and the backend        " include("integration/rgrad_backend.jl")
    @safetestset "Default gradient             " include("integration/default_gradient.jl")
    @safetestset "Storage gradient             " include("parameter_protocol.jl")
    @safetestset "== through the storage       " include("integration/storage_equality.jl")
    @safetestset "device solve!                " include("integration/device_solve.jl")
    @safetestset "copyto! crosses backends     " include("integration/device_copyto.jl")
    @safetestset "device orthonormalization    " include("integration/device_orthonormalization.jl")
    @safetestset "device multiply              " include("integration/device_multiply.jl")
    @safetestset "device products and sums     " include("integration/device_products.jl")
    @safetestset "mixed-backend refusal        " include("integration/mixed_backend_refusal.jl")
end
if "slow" in GROUPS
    @safetestset "Doctests                     " include("quality/doctests.jl")
end
if "metal" in GROUPS
    @safetestset "Metal                        " include("devices/metal.jl")
end
