using SafeTestsets

const GROUPS = isempty(ARGS) ? ["core", "slow"] : ARGS

if "core" in GROUPS
    @safetestset "Exports                      " include("exports.jl")
    @safetestset "Public surface               " include("public_surface.jl")
    @safetestset "Aqua: piracy and compat      " include("quality/aqua.jl")
    @safetestset "ExplicitImports              " include("quality/explicit_imports.jl")
    @safetestset "Own-vs-own ambiguities       " include("ambiguities.jl")
    @safetestset "Container/section copies     " include("container_section_copy.jl")
    @safetestset "Stiefel Manifold             " include("manifolds/stiefel_manifold.jl")
    @safetestset "Grassmann Manifold           " include("manifolds/grassmann_manifold.jl")
    @safetestset "Manifold Broadcast           " include("manifolds/broadcast.jl")
    @safetestset "Symplectic Stiefel Manifold  " include("manifolds/symplectic_stiefel_manifold.jl")
    @safetestset "Symplectic on a backend      " include("manifolds/symplectic_backend.jl")
    @safetestset "Symplectic SR Decomposition  " include("decompositions/symplectic_sr.jl")
    @safetestset "Backend default eltype       " include("default_eltype.jl")
    @safetestset "Backend eltype check         " include("backend_eltype_check.jl")
    @safetestset "Stiefel Projection           " include("special_matrices/stiefel_projetion.jl")
    @safetestset "Skew-Symmetric Matrix        " include("special_matrices/skew_symmetric.jl")
    @safetestset "Symmetric Matrix             " include("special_matrices/symmetric_matrix.jl")
    @safetestset "ProjectTo natural cotangent  " include("special_matrices/project_to.jl")
    @safetestset "Triangular Matrices          " include("special_matrices/triangular.jl")
    @safetestset "Mutating Return Values       " include("special_matrices/scalar_mul_return_value.jl")
    @safetestset "Optimizer Primitives         " include("special_matrices/optimizer_primitives.jl")
    @safetestset "Grassmann Lie Alg Hor        " include("lie_algebras/grassmann_lie_algebra_horizontal.jl")
    @safetestset "Stiefel Lie Alg Hor          " include("lie_algebras/stiefel_lie_algebra_horizontal.jl")
    @safetestset "Retractions                  " include("retractions/retractions.jl")
    @safetestset "Exponential Accuracy         " include("retractions/exponential_accuracy.jl")
    @safetestset "Ω functions                  " include("global_sections/omega_functions.jl")
    @safetestset "Global global_sections       " include("global_sections/global_sections.jl")
    @safetestset "Optimizer Convergence        " include("verification/svd_optim.jl")
    @safetestset "Optimizers                   " include("optimizer_tests.jl")
    @safetestset "Optimizer phase observer     " include("optimizer_observer.jl")
    @safetestset "Optimizer Problems           " include("optimizer_problems.jl")
    @safetestset "Optimizer Status             " include("optimizer_status_tests.jl")
    @safetestset "Descent Direction            " include("descent_direction_tests.jl")
    @safetestset "Quasi-Newton Secant Pair     " include("quasi_newton_secant_tests.jl")
    @safetestset "Manifold Line Search         " include("manifold_linesearch_tests.jl")
    @safetestset "Manifold Optimizers          " include("manifold_optimizers_with_new_interface.jl")
    @safetestset "Grassmann Optimizers         " include("grassmann_optimizer_tests.jl")
    @safetestset "Optimizer State Init         " include("optimizer_state_initialization.jl")
    @safetestset "Optimizer State Accessors    " include("optimizer_state_accessors.jl")
    @safetestset "Optimizer Step Formulas      " include("optimizer_step_formulas.jl")
    @safetestset "Adam + Euclidean decay       " include("adam_with_euclidean_decay.jl")
    @safetestset "Adam + decaying step         " include("adam_optimizer_with_decay.jl")
    @safetestset "Scalar-moment Adam           " include("scalar_moment_adam.jl")
    @safetestset "Training step                " include("training_optimizer.jl")
    @safetestset "Flat Parameters              " include("flat_parameters.jl")
    @safetestset "NeuralNetworkParameters      " include("neural_network_parameters_protocol.jl")
    @safetestset "Container Parameters         " include("network_parameters_optimizer.jl")
    @safetestset "Flat Buffer Allocations      " include("flat_buffer_allocations.jl")
    @safetestset "changebackend                " include("changebackend.jl")
    @safetestset "similar keeps the backend    " include("similar_backend.jl")
    @safetestset "rgrad matches the backend    " include("gradient_backend.jl")
    @safetestset "copyto! crosses backends     " include("device_copyto.jl")
    @safetestset "device orthonormalization    " include("device_orthonormalization.jl")
    @safetestset "device multiply              " include("device_multiply.jl")
    @safetestset "device products and sums     " include("device_products.jl")
    @safetestset "mixed-backend refusal        " include("mixed_backend_refusal.jl")
end
if "slow" in GROUPS
    @safetestset "Doctests                     " include("quality/doctests.jl")
end
if "metal" in GROUPS
    @safetestset "Metal                        " include("devices/metal.jl")
end
