name = "GeometricOptimizers"
uuid = "fc236c15-5557-4942-aa65-b650f329279e"
authors = ["Michael Kraus"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
