# Reference iterates of GeometricMachineLearning 0.8's `optimization_step!`, for
# `test/training_optimizer.jl`.
#
# GML 0.8 requires GeometricOptimizers 0.8, so it cannot be a test dependency of this package. This
# script runs in its own environment, next to it, and writes the iterates as Julia literals:
#
#     julia --startup-file=no --project=scripts/gml_reference scripts/gml_reference/generate.jl
#
# Format the output with JuliaFormatter afterwards, as every `.jl` file in the repository is.
#
# The output is `test/data/gml_reference.jl`. Each entry holds, for one model, one element type and
# one method, the initial parameters, the gradients, the parameters after every step, and the
# `completions`: the random orthonormal completion `λ` of each manifold leaf's `GlobalSection` in the
# optimizer state, `nothing` for the other leaves.
#
# The step on a manifold depends on the completion, `Adam`'s visibly so, and seeding the RNG equally
# on both sides does not make the completions equal. GML 0.8 builds one state per layer, and each
# state draws a random `x̄` for each manifold leaf after its sections, so a later layer's section is
# drawn at a different point of the stream than a `TrainingOptimizer`'s, which draws every section
# first. And this package orthonormalises a completion twice where GeometricOptimizers 0.8.0 does it
# once, which moves it by round-off. So the test copies these completions into its own state before
# the first step.
using GeometricMachineLearning, KernelAbstractions, Random
import GeometricOptimizers as GO
using NeuralNetworkParameters: mapparameters, params

const SEED = 123
const NSTEPS = 3

const MODELS = [
    "StiefelLayer + Dense + GrassmannLayer" =>
        () -> Chain(
            StiefelLayer(6, 3), Dense(6, 6, tanh), GrassmannLayer(6, 2)),
    "MultiHeadAttention(Stiefel = true) + Dense" =>
        () -> Chain(
            MultiHeadAttention(4, 2; Stiefel = true), Dense(4, 4, tanh)),
    "LASympNet(4)" => () -> LASympNet(4),
    "GSympNet(4)" => () -> GSympNet(4),
    "VolumePreservingAttention(skew_sym = true)" =>
        () -> Chain(VolumePreservingAttention(4, 3; skew_sym = true)),
    "VolumePreservingLowerLayer + VolumePreservingUpperLayer" =>
        () -> Chain(VolumePreservingLowerLayer(4), VolumePreservingUpperLayer(4))
]

const METHODS = [
    (:GradientMethod, T -> GO.GradientMethod(), 1e-2),
    (:MomentumMethod, T -> GO.MomentumMethod(0.5), 1e-2),
    (:Adam, T -> GO.Adam(T), 1e-3)
]

# A Euclidean gradient of the shape GML's pullback gives each leaf.
_gradient(x::GO.Manifold{T}) where {T} = rand(T, size(x)...)
const VectorStorage = Union{
    GO.SymmetricMatrix, GO.SkewSymMatrix, GO.LowerTriangular, GO.UpperTriangular}
function _gradient(x::VectorStorage)
    typeof(x).name.wrapper(rand(eltype(x), length(x.S)), x.n)
end
_gradient(x::AbstractArray{T}) where {T} = rand(T, size(x)...)

# Julia source that rebuilds a leaf or a tree, in the names of this package's `main`: the strictly
# triangular matrices were `LowerTriangular` and `UpperTriangular` in 0.8. `repr` of a float array
# round-trips exactly.
_source(x::GO.StiefelManifold) = "StiefelManifold($(repr(Matrix(x.A))))"
_source(x::GO.GrassmannManifold) = "GrassmannManifold($(repr(Matrix(x.A))))"
_name(::GO.SymmetricMatrix) = "SymmetricMatrix"
_name(::GO.SkewSymMatrix) = "SkewSymMatrix"
_name(::GO.LowerTriangular) = "StrictlyLowerTriangular"
_name(::GO.UpperTriangular) = "StrictlyUpperTriangular"
_source(x::VectorStorage) = "$(_name(x))($(repr(Vector(x.S))), $(x.n))"
_source(x::AbstractArray) = repr(x)
_source(λY::GO.GlobalSection) = λY.λ === nothing ? "nothing" : repr(Matrix(λY.λ))
_source(state::GO.OptimizerState) = _source(GO.section(state))
function _source(x::NamedTuple)
    "(" * join(("$(k) = $(_source(v))" for (k, v) in pairs(x)), ", ") * ",)"
end

function reference(model, T, method, η)
    Random.seed!(1)
    nn = NeuralNetwork(model(), CPU(), T)
    ps = nn.params
    x₀ = _source(params(ps))
    gradients = [mapparameters(_gradient, ps) for _ in 1:NSTEPS]
    gradient_sources = [_source(params(dp)) for dp in gradients]
    Random.seed!(SEED)
    opt = Optimizer(method, ps; step_size = η)
    # GML 0.8 keeps one state per layer, so the tree of states has the shape of the parameters
    completions = _source(opt.state)
    λY = GlobalSection(ps)
    iterates = String[]
    for dp in gradients
        optimization_step!(opt, λY, ps, params(dp))
        push!(iterates, _source(params(ps)))
    end
    x₀, completions, gradient_sources, iterates
end

function main(path)
    open(path, "w") do io
        println(io,
            "# Generated by `scripts/gml_reference/generate.jl` with GeometricMachineLearning 0.8.0 and")
        println(io, "# GeometricOptimizers 0.8.0. Do not edit; regenerate.")
        println(io, "const GML_REFERENCE = [")
        for (name, model) in MODELS, T in (Float32, Float64), (mname, method, η) in METHODS
            x₀, completions, gradients, iterates = reference(model, T, method(T), η)
            println(io, "    (model = $(repr(name)), T = $(T), method = $(repr(mname)), η = $(η),")
            println(io, "        x₀ = $(x₀),")
            println(io, "        completions = $(completions),")
            println(io, "        gradients = [$(join(gradients, ", "))],")
            println(io, "        iterates = [$(join(iterates, ", "))]),")
        end
        println(io, "]")
    end
end

main(joinpath(@__DIR__, "..", "..", "test", "data", "gml_reference.jl"))
